linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 4
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - emptyStringTest
      - hugeParam
      - ifElseChain
      - paramTypeCombine
      - importShadow
      - sprintfQuotedString
      - singleCaseSwitch
      - exitAfterDefer # Remove in the future
      - whyNoLint # Remove in the future
      - rangeValCopy # Remove in the future
      - defaultCaseOrder # Remove in the future
      - deferInLoop # Remove in the future
  gocyclo:
    min-complexity: 30 # Recommended between 10-20
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
  goimports:
    local-prefixes: github.com/tsaikd/gogstash

  lll:
    line-length: 110
  misspell:
    locale: US
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  revive:
    rules:
      - name: unexported-return
        disabled: true
      - name: unused-parameter

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
      #- dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
      #- gomnd
    - goprintffuncname
      #- gosec
    - gosimple
    - govet
    - ineffassign
      #- lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
      #- revive
    - staticcheck
      #- stylecheck
    - typecheck
      #- unconvert
      #- unparam
    - unused
    - whitespace

run:
  timeout: 5m
